[package]
name = "product-service-algonquin-pet-store"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
dotenv = "0.15"                                # For loading environment variables in development
